/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class antenna {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected antenna(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(antenna obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libcampoclsJNI.delete_antenna(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void setDebugAntenne(SWIGTYPE_p_string value) {
    libcampoclsJNI.antenna_debugAntenne_set(SWIGTYPE_p_string.getCPtr(value));
  }

  public static SWIGTYPE_p_string getDebugAntenne() {
    return new SWIGTYPE_p_string(libcampoclsJNI.antenna_debugAntenne_get(), true);
  }

  public void setModified(SWIGTYPE_p_setT_string_t value) {
    libcampoclsJNI.antenna_Modified_set(swigCPtr, this, SWIGTYPE_p_setT_string_t.getCPtr(value));
  }

  public SWIGTYPE_p_setT_string_t getModified() {
    return new SWIGTYPE_p_setT_string_t(libcampoclsJNI.antenna_Modified_get(swigCPtr, this), true);
  }

  public antenna() {
    this(libcampoclsJNI.new_antenna__SWIG_0(), true);
  }

  public antenna(antenna oAnt) {
    this(libcampoclsJNI.new_antenna__SWIG_1(antenna.getCPtr(oAnt), oAnt), true);
  }

  public int setDA(String dbFld, String valDato) {
    return libcampoclsJNI.antenna_setDA(swigCPtr, this, dbFld, valDato);
  }

  public String getDA(String dbFld) {
    return libcampoclsJNI.antenna_getDA(swigCPtr, this, dbFld);
  }

  public void setModified(String dbFld) {
    libcampoclsJNI.antenna_setModified(swigCPtr, this, dbFld);
  }

  public void noModified(String dbFld) {
    libcampoclsJNI.antenna_noModified(swigCPtr, this, dbFld);
  }

  public boolean isModified(String dbFld) {
    return libcampoclsJNI.antenna_isModified(swigCPtr, this, dbFld);
  }

  public int getIdAntenna() {
    return libcampoclsJNI.antenna_getIdAntenna(swigCPtr, this);
  }

  public int getIdPadre() {
    return libcampoclsJNI.antenna_getIdPadre(swigCPtr, this);
  }

  public double getX() {
    return libcampoclsJNI.antenna_getX(swigCPtr, this);
  }

  public double getY() {
    return libcampoclsJNI.antenna_getY(swigCPtr, this);
  }

  public double getH() {
    return libcampoclsJNI.antenna_getH(swigCPtr, this);
  }

  public int getNumTx() {
    return libcampoclsJNI.antenna_getNumTx(swigCPtr, this);
  }

  public double getPotenzaTx() {
    return libcampoclsJNI.antenna_getPotenzaTx(swigCPtr, this);
  }

  public double getTilt() {
    return libcampoclsJNI.antenna_getTilt(swigCPtr, this);
  }

  public double getDirezione() {
    return libcampoclsJNI.antenna_getDirezione(swigCPtr, this);
  }

  public boolean getAttiva() {
    return libcampoclsJNI.antenna_getAttiva(swigCPtr, this);
  }

  public boolean getAntCalc() {
    return libcampoclsJNI.antenna_getAntCalc(swigCPtr, this);
  }

  public int getIdImpianto() {
    return libcampoclsJNI.antenna_getIdImpianto(swigCPtr, this);
  }

  public int getIdModello() {
    return libcampoclsJNI.antenna_getIdModello(swigCPtr, this);
  }

  public int getIdServizio() {
    return libcampoclsJNI.antenna_getIdServizio(swigCPtr, this);
  }

  public int getIdPolar() {
    return libcampoclsJNI.antenna_getIdPolar(swigCPtr, this);
  }

  public int getIdStato() {
    return libcampoclsJNI.antenna_getIdStato(swigCPtr, this);
  }

  public double getFreqMin() {
    return libcampoclsJNI.antenna_getFreqMin(swigCPtr, this);
  }

  public double getFreqMax() {
    return libcampoclsJNI.antenna_getFreqMax(swigCPtr, this);
  }

  public double getFrequenza() {
    return libcampoclsJNI.antenna_getFrequenza(swigCPtr, this);
  }

  public double getFase() {
    return libcampoclsJNI.antenna_getFase(swigCPtr, this);
  }

  public double getAlfa24() {
    return libcampoclsJNI.antenna_getAlfa24(swigCPtr, this);
  }

  public double getAttPC() {
    return libcampoclsJNI.antenna_getAttPC(swigCPtr, this);
  }

  public double getAttDTX() {
    return libcampoclsJNI.antenna_getAttDTX(swigCPtr, this);
  }

  public double getAttTDD() {
    return libcampoclsJNI.antenna_getAttTDD(swigCPtr, this);
  }

  public double getPotenzaPerc() {
    return libcampoclsJNI.antenna_getPotenzaPerc(swigCPtr, this);
  }

  public String getDataIn() {
    return libcampoclsJNI.antenna_getDataIn(swigCPtr, this);
  }

  public String getDataFin() {
    return libcampoclsJNI.antenna_getDataFin(swigCPtr, this);
  }

  public String getNote1() {
    return libcampoclsJNI.antenna_getNote1(swigCPtr, this);
  }

  public String getImmagine() {
    return libcampoclsJNI.antenna_getImmagine(swigCPtr, this);
  }

  public modello getModello() {
    long cPtr = libcampoclsJNI.antenna_getModello(swigCPtr, this);
    return (cPtr == 0) ? null : new modello(cPtr, false);
  }

  public void setModello(modello mod) {
    libcampoclsJNI.antenna_setModello(swigCPtr, this, modello.getCPtr(mod), mod);
  }

  public void setIdAnt(int id) {
    libcampoclsJNI.antenna_setIdAnt(swigCPtr, this, id);
  }

  public void setPot(double pW) {
    libcampoclsJNI.antenna_setPot(swigCPtr, this, pW);
  }

  public double getPot() {
    return libcampoclsJNI.antenna_getPot(swigCPtr, this);
  }

}
