/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class gruppoImpianti {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected gruppoImpianti(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(gruppoImpianti obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libcampoclsJNI.delete_gruppoImpianti(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setImpianti(SWIGTYPE_p_std__vectorT_impianto_p_t value) {
    libcampoclsJNI.gruppoImpianti_impianti_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_impianto_p_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_impianto_p_t getImpianti() {
    long cPtr = libcampoclsJNI.gruppoImpianti_impianti_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_impianto_p_t(cPtr, false);
  }

  public void setItI(SWIGTYPE_p_std__vectorT_impianto_p_t__iterator value) {
    libcampoclsJNI.gruppoImpianti_itI_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_impianto_p_t__iterator.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_impianto_p_t__iterator getItI() {
    long cPtr = libcampoclsJNI.gruppoImpianti_itI_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_impianto_p_t__iterator(cPtr, false);
  }

  public void setMd5FileImp(String value) {
    libcampoclsJNI.gruppoImpianti_md5FileImp_set(swigCPtr, this, value);
  }

  public String getMd5FileImp() {
    return libcampoclsJNI.gruppoImpianti_md5FileImp_get(swigCPtr, this);
  }

  public gruppoImpianti() {
    this(libcampoclsJNI.new_gruppoImpianti__SWIG_0(), true);
  }

  public gruppoImpianti(gruppoImpianti gImp) {
    this(libcampoclsJNI.new_gruppoImpianti__SWIG_1(gruppoImpianti.getCPtr(gImp), gImp), true);
  }

  public void creaFileErrori() {
    libcampoclsJNI.gruppoImpianti_creaFileErrori(swigCPtr, this);
  }

  public String getStrErrori() {
    return libcampoclsJNI.gruppoImpianti_getStrErrori(swigCPtr, this);
  }

  public void azzeraStrErrori() {
    libcampoclsJNI.gruppoImpianti_azzeraStrErrori(swigCPtr, this);
  }

  public void deleteImpianti() {
    libcampoclsJNI.gruppoImpianti_deleteImpianti(swigCPtr, this);
  }

  public int addImpianto(impianto newImp) {
    return libcampoclsJNI.gruppoImpianti_addImpianto(swigCPtr, this, impianto.getCPtr(newImp), newImp);
  }

  public int associaModelli() {
    return libcampoclsJNI.gruppoImpianti_associaModelli(swigCPtr, this);
  }

  public void beginIter() {
    libcampoclsJNI.gruppoImpianti_beginIter(swigCPtr, this);
  }

  public impianto nextItem() {
    long cPtr = libcampoclsJNI.gruppoImpianti_nextItem(swigCPtr, this);
    return (cPtr == 0) ? null : new impianto(cPtr, false);
  }

  public impianto getImpById(int id) {
    long cPtr = libcampoclsJNI.gruppoImpianti_getImpById(swigCPtr, this, id);
    return (cPtr == 0) ? null : new impianto(cPtr, false);
  }

  public int removeImpById(int id) {
    return libcampoclsJNI.gruppoImpianti_removeImpById(swigCPtr, this, id);
  }

  public antenna getAntById(int id) {
    long cPtr = libcampoclsJNI.gruppoImpianti_getAntById(swigCPtr, this, id);
    return (cPtr == 0) ? null : new antenna(cPtr, false);
  }

  public int removeAntById(int id) {
    return libcampoclsJNI.gruppoImpianti_removeAntById(swigCPtr, this, id);
  }

  public int leggiImpiantiAntenneXML(String nomeFile) {
    return libcampoclsJNI.gruppoImpianti_leggiImpiantiAntenneXML(swigCPtr, this, nomeFile);
  }

  public int scriviImpiantiAntenneXML(String nomeFile) {
    return libcampoclsJNI.gruppoImpianti_scriviImpiantiAntenneXML(swigCPtr, this, nomeFile);
  }

  public int leggiModelliDiagrammiXML(String nomeFile) {
    return libcampoclsJNI.gruppoImpianti_leggiModelliDiagrammiXML(swigCPtr, this, nomeFile);
  }

  public int scriviModelliDiagrammiXML(String nomeFile) {
    return libcampoclsJNI.gruppoImpianti_scriviModelliDiagrammiXML(swigCPtr, this, nomeFile);
  }

  public impianto newImpianto() {
    long cPtr = libcampoclsJNI.gruppoImpianti_newImpianto(swigCPtr, this);
    return (cPtr == 0) ? null : new impianto(cPtr, false);
  }

  public modello newModello() {
    long cPtr = libcampoclsJNI.gruppoImpianti_newModello(swigCPtr, this);
    return (cPtr == 0) ? null : new modello(cPtr, false);
  }

  public gruppoModelli getGruppoModelli() {
    long cPtr = libcampoclsJNI.gruppoImpianti_getGruppoModelli(swigCPtr, this);
    return (cPtr == 0) ? null : new gruppoModelli(cPtr, false);
  }

  public modello getModById(int id) {
    long cPtr = libcampoclsJNI.gruppoImpianti_getModById(swigCPtr, this, id);
    return (cPtr == 0) ? null : new modello(cPtr, false);
  }

  public int removeModById(int id) {
    return libcampoclsJNI.gruppoImpianti_removeModById(swigCPtr, this, id);
  }

  public int getMinNegAntID() {
    return libcampoclsJNI.gruppoImpianti_getMinNegAntID(swigCPtr, this);
  }

  public int getMinNegImpID() {
    return libcampoclsJNI.gruppoImpianti_getMinNegImpID(swigCPtr, this);
  }

  public int setMd5(String valDato) {
    return libcampoclsJNI.gruppoImpianti_setMd5(swigCPtr, this, valDato);
  }

  public String getMd5() {
    return libcampoclsJNI.gruppoImpianti_getMd5(swigCPtr, this);
  }

  public int somma(impianto newImp) {
    return libcampoclsJNI.gruppoImpianti_somma__SWIG_0(swigCPtr, this, impianto.getCPtr(newImp), newImp);
  }

  public int somma(gruppoImpianti newGrImp) {
    return libcampoclsJNI.gruppoImpianti_somma__SWIG_1(swigCPtr, this, gruppoImpianti.getCPtr(newGrImp), newGrImp);
  }

  public void inizializzaCalcolo() {
    libcampoclsJNI.gruppoImpianti_inizializzaCalcolo(swigCPtr, this);
  }

  public int setInfluenti(String nomeFileShape) {
    return libcampoclsJNI.gruppoImpianti_setInfluenti__SWIG_0(swigCPtr, this, nomeFileShape);
  }

  public void setInfluenti(SWIGTYPE_p_SHPObject aInf) {
    libcampoclsJNI.gruppoImpianti_setInfluenti__SWIG_1(swigCPtr, this, SWIGTYPE_p_SHPObject.getCPtr(aInf));
  }

  public int pnpoly(int nvert, SWIGTYPE_p_double vertx, SWIGTYPE_p_double verty, double testx, double testy) {
    return libcampoclsJNI.gruppoImpianti_pnpoly(swigCPtr, this, nvert, SWIGTYPE_p_double.getCPtr(vertx), SWIGTYPE_p_double.getCPtr(verty), testx, testy);
  }

  public void ordinaSorgenti() {
    libcampoclsJNI.gruppoImpianti_ordinaSorgenti(swigCPtr, this);
  }

  public gruppoImpianti getActiveImp() {
    long cPtr = libcampoclsJNI.gruppoImpianti_getActiveImp(swigCPtr, this);
    return (cPtr == 0) ? null : new gruppoImpianti(cPtr, false);
  }

  public int size() {
    return libcampoclsJNI.gruppoImpianti_size(swigCPtr, this);
  }

}
