/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class gruppoModelli {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected gruppoModelli(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(gruppoModelli obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libcampoclsJNI.delete_gruppoModelli(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setModelli(SWIGTYPE_p_std__vectorT_modello_p_t value) {
    libcampoclsJNI.gruppoModelli_modelli_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_modello_p_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_modello_p_t getModelli() {
    long cPtr = libcampoclsJNI.gruppoModelli_modelli_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_modello_p_t(cPtr, false);
  }

  public void setItM(SWIGTYPE_p_std__vectorT_modello_p_t__iterator value) {
    libcampoclsJNI.gruppoModelli_itM_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_modello_p_t__iterator.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_modello_p_t__iterator getItM() {
    long cPtr = libcampoclsJNI.gruppoModelli_itM_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_modello_p_t__iterator(cPtr, false);
  }

  public void setMd5FileMod(String value) {
    libcampoclsJNI.gruppoModelli_md5FileMod_set(swigCPtr, this, value);
  }

  public String getMd5FileMod() {
    return libcampoclsJNI.gruppoModelli_md5FileMod_get(swigCPtr, this);
  }

  public gruppoModelli() {
    this(libcampoclsJNI.new_gruppoModelli__SWIG_0(), true);
  }

  public gruppoModelli(gruppoModelli gMod) {
    this(libcampoclsJNI.new_gruppoModelli__SWIG_1(gruppoModelli.getCPtr(gMod), gMod), true);
  }

  public int somma(modello newMod) {
    return libcampoclsJNI.gruppoModelli_somma__SWIG_0(swigCPtr, this, modello.getCPtr(newMod), newMod);
  }

  public int getMinNegID() {
    return libcampoclsJNI.gruppoModelli_getMinNegID(swigCPtr, this);
  }

  public int somma(gruppoModelli aGM) {
    return libcampoclsJNI.gruppoModelli_somma__SWIG_1(swigCPtr, this, gruppoModelli.getCPtr(aGM), aGM);
  }

  public void deleteModelli() {
    libcampoclsJNI.gruppoModelli_deleteModelli(swigCPtr, this);
  }

  public int size() {
    return libcampoclsJNI.gruppoModelli_size(swigCPtr, this);
  }

  public int addModello(modello newMod) {
    return libcampoclsJNI.gruppoModelli_addModello(swigCPtr, this, modello.getCPtr(newMod), newMod);
  }

  public modello getModById(int id) {
    long cPtr = libcampoclsJNI.gruppoModelli_getModById(swigCPtr, this, id);
    return (cPtr == 0) ? null : new modello(cPtr, false);
  }

  public int removeModById(int id) {
    return libcampoclsJNI.gruppoModelli_removeModById(swigCPtr, this, id);
  }

  public void beginIter() {
    libcampoclsJNI.gruppoModelli_beginIter(swigCPtr, this);
  }

  public modello nextItem() {
    long cPtr = libcampoclsJNI.gruppoModelli_nextItem(swigCPtr, this);
    return (cPtr == 0) ? null : new modello(cPtr, false);
  }

  public int leggiModelliDiagrammiXML(String nomeFile) {
    return libcampoclsJNI.gruppoModelli_leggiModelliDiagrammiXML(swigCPtr, this, nomeFile);
  }

  public int scriviModelliDiagrammiXML(String nomeFile) {
    return libcampoclsJNI.gruppoModelli_scriviModelliDiagrammiXML(swigCPtr, this, nomeFile);
  }

}
