/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface libcampoclsConstants {
  public final static int TRUE = libcampoclsJNI.TRUE_get();
  public final static int FALSE = libcampoclsJNI.FALSE_get();
  public final static int sz_TERMINATOR = libcampoclsJNI.sz_TERMINATOR_get();
  public final static int MAX_CHARS = libcampoclsJNI.MAX_CHARS_get();
  public final static double PIGRECO = libcampoclsJNI.PIGRECO_get();
  public final static double ZCAR = libcampoclsJNI.ZCAR_get();
  public final static double LAMBDA = libcampoclsJNI.LAMBDA_get();
  public final static int GRADI = libcampoclsJNI.GRADI_get();
  public final static int N_ANTENNE_MAX = libcampoclsJNI.N_ANTENNE_MAX_get();
  public final static int TIPI_ANT_MAX = libcampoclsJNI.TIPI_ANT_MAX_get();
  public final static int LEN_WHERE_IDMOD = libcampoclsJNI.LEN_WHERE_IDMOD_get();
  public final static int SIZE_CONNSTRINGOUT = libcampoclsJNI.SIZE_CONNSTRINGOUT_get();
  public final static int SIZE_STR_LOG = libcampoclsJNI.SIZE_STR_LOG_get();
  public final static int NODATA = libcampoclsJNI.NODATA_get();
  public final static double RADQ2 = libcampoclsJNI.RADQ2_get();
}
