/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class libcampocls implements libcampoclsConstants {
  public static int getSTR_FLD_MOD() {
    return libcampoclsJNI.STR_FLD_MOD_get();
  }

  public static int getSTR_INT_MOD() {
    return libcampoclsJNI.STR_INT_MOD_get();
  }

  public static int getSTR_DOUBLE_MOD() {
    return libcampoclsJNI.STR_DOUBLE_MOD_get();
  }

  public static int getSTR_BOOL_MOD() {
    return libcampoclsJNI.STR_BOOL_MOD_get();
  }

  public static int getSTR_FLD() {
    return libcampoclsJNI.STR_FLD_get();
  }

  public static int getSTR_INT() {
    return libcampoclsJNI.STR_INT_get();
  }

  public static int getSTR_DOUBLE() {
    return libcampoclsJNI.STR_DOUBLE_get();
  }

  public static int getSTR_BOOL() {
    return libcampoclsJNI.STR_BOOL_get();
  }

  public static int getNUM_MOD_FLD() {
    return libcampoclsJNI.NUM_MOD_FLD_get();
  }

  public static SWIGTYPE_p_a_20__char getMOD_FLD() {
    long cPtr = libcampoclsJNI.MOD_FLD_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_20__char(cPtr, false);
  }

  public static int getNUM_IMP_FLD() {
    return libcampoclsJNI.NUM_IMP_FLD_get();
  }

  public static SWIGTYPE_p_a_20__char getIMP_FLD() {
    long cPtr = libcampoclsJNI.IMP_FLD_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_20__char(cPtr, false);
  }

  public static int getNUM_ANT_FLD() {
    return libcampoclsJNI.NUM_ANT_FLD_get();
  }

  public static SWIGTYPE_p_a_20__char getANT_FLD() {
    long cPtr = libcampoclsJNI.ANT_FLD_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_20__char(cPtr, false);
  }

}
