/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class modello {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected modello(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(modello obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libcampoclsJNI.delete_modello(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void setDebugModelli(SWIGTYPE_p_string value) {
    libcampoclsJNI.modello_debugModelli_set(SWIGTYPE_p_string.getCPtr(value));
  }

  public static SWIGTYPE_p_string getDebugModelli() {
    return new SWIGTYPE_p_string(libcampoclsJNI.modello_debugModelli_get(), true);
  }

  public void setNumOgradi(int value) {
    libcampoclsJNI.modello_numOgradi_set(swigCPtr, this, value);
  }

  public int getNumOgradi() {
    return libcampoclsJNI.modello_numOgradi_get(swigCPtr, this);
  }

  public void setNumVgradi(int value) {
    libcampoclsJNI.modello_numVgradi_set(swigCPtr, this, value);
  }

  public int getNumVgradi() {
    return libcampoclsJNI.modello_numVgradi_get(swigCPtr, this);
  }

  public modello() {
    this(libcampoclsJNI.new_modello__SWIG_0(), true);
  }

  public modello(modello oMod) {
    this(libcampoclsJNI.new_modello__SWIG_1(modello.getCPtr(oMod), oMod), true);
  }

  public int setDM(String dbFld, String valDato) {
    return libcampoclsJNI.modello_setDM(swigCPtr, this, dbFld, valDato);
  }

  public String getDM(String dbFld) {
    return libcampoclsJNI.modello_getDM(swigCPtr, this, dbFld);
  }

  public int getIdModello() {
    return libcampoclsJNI.modello_getIdModello(swigCPtr, this);
  }

  public double getGuadagno() {
    return libcampoclsJNI.modello_getGuadagno(swigCPtr, this);
  }

  public double getLunghezza() {
    return libcampoclsJNI.modello_getLunghezza(swigCPtr, this);
  }

  public double getFrequenza() {
    return libcampoclsJNI.modello_getFrequenza(swigCPtr, this);
  }

  public String getNomeMod() {
    return libcampoclsJNI.modello_getNomeMod(swigCPtr, this);
  }

  public String getMarca() {
    return libcampoclsJNI.modello_getMarca(swigCPtr, this);
  }

  public String getNote1() {
    return libcampoclsJNI.modello_getNote1(swigCPtr, this);
  }

  public String getImmagine() {
    return libcampoclsJNI.modello_getImmagine(swigCPtr, this);
  }

  public int getSizeAttO() {
    return libcampoclsJNI.modello_getSizeAttO(swigCPtr, this);
  }

  public int getSizeGrdO() {
    return libcampoclsJNI.modello_getSizeGrdO(swigCPtr, this);
  }

  public int getSizeAttV() {
    return libcampoclsJNI.modello_getSizeAttV(swigCPtr, this);
  }

  public int getSizeGrdV() {
    return libcampoclsJNI.modello_getSizeGrdV(swigCPtr, this);
  }

  public double getAttO(long i) {
    return libcampoclsJNI.modello_getAttO(swigCPtr, this, i);
  }

  public double getGrdO(long i) {
    return libcampoclsJNI.modello_getGrdO(swigCPtr, this, i);
  }

  public double getAttV(long i) {
    return libcampoclsJNI.modello_getAttV(swigCPtr, this, i);
  }

  public double getGrdV(long i) {
    return libcampoclsJNI.modello_getGrdV(swigCPtr, this, i);
  }

  public void setIdMod(int id) {
    libcampoclsJNI.modello_setIdMod(swigCPtr, this, id);
  }

  public void setAttO(long i, double valDato) {
    libcampoclsJNI.modello_setAttO(swigCPtr, this, i, valDato);
  }

  public void setGrdO(long i, double valDato) {
    libcampoclsJNI.modello_setGrdO(swigCPtr, this, i, valDato);
  }

  public void setAttV(long i, double valDato) {
    libcampoclsJNI.modello_setAttV(swigCPtr, this, i, valDato);
  }

  public void setGrdV(long i, double valDato) {
    libcampoclsJNI.modello_setGrdV(swigCPtr, this, i, valDato);
  }

  public void addAttO(double valDato) {
    libcampoclsJNI.modello_addAttO(swigCPtr, this, valDato);
  }

  public void addGrdO(double valDato) {
    libcampoclsJNI.modello_addGrdO(swigCPtr, this, valDato);
  }

  public void addAttV(double valDato) {
    libcampoclsJNI.modello_addAttV(swigCPtr, this, valDato);
  }

  public void addGrdV(double valDato) {
    libcampoclsJNI.modello_addGrdV(swigCPtr, this, valDato);
  }

}
