/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class moduloCalcolo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected moduloCalcolo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(moduloCalcolo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libcampoclsJNI.delete_moduloCalcolo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public moduloCalcolo() {
    this(libcampoclsJNI.new_moduloCalcolo(), true);
  }

  public gruppoImpianti getGruppoImpianti() {
    long cPtr = libcampoclsJNI.moduloCalcolo_getGruppoImpianti(swigCPtr, this);
    return (cPtr == 0) ? null : new gruppoImpianti(cPtr, false);
  }

  public double getPotTotPunto() {
    return libcampoclsJNI.moduloCalcolo_getPotTotPunto(swigCPtr, this);
  }

  public double getPotTotPuntoH() {
    return libcampoclsJNI.moduloCalcolo_getPotTotPuntoH(swigCPtr, this);
  }

  public int getIndexString() {
    return libcampoclsJNI.moduloCalcolo_getIndexString(swigCPtr, this);
  }

  public int getHandleWinProgrMain() {
    return libcampoclsJNI.moduloCalcolo_getHandleWinProgrMain(swigCPtr, this);
  }

  public void setGruppoImpianti(gruppoImpianti gruppoImpianto) {
    libcampoclsJNI.moduloCalcolo_setGruppoImpianti(swigCPtr, this, gruppoImpianti.getCPtr(gruppoImpianto), gruppoImpianto);
  }

  public void setPotTotPunto(double valDato) {
    libcampoclsJNI.moduloCalcolo_setPotTotPunto(swigCPtr, this, valDato);
  }

  public void setPotTotPuntoH(double valDato) {
    libcampoclsJNI.moduloCalcolo_setPotTotPuntoH(swigCPtr, this, valDato);
  }

  public void setIndexString(int valDato) {
    libcampoclsJNI.moduloCalcolo_setIndexString(swigCPtr, this, valDato);
  }

  public void setHandleWinProgrMain(int valDato) {
    libcampoclsJNI.moduloCalcolo_setHandleWinProgrMain(swigCPtr, this, valDato);
  }

  public int calcoloOrizz(double xGB, double yGB, double dx, double dy, double cellSize, double altitudine, String strFileOutput, String strFileOutputH, String strFileOutputS, int tipoCampo, int tipoRaster) {
    return libcampoclsJNI.moduloCalcolo_calcoloOrizz(swigCPtr, this, xGB, yGB, dx, dy, cellSize, altitudine, strFileOutput, strFileOutputH, strFileOutputS, tipoCampo, tipoRaster);
  }

  public int calcoloVert(double xGB0, double yGB0, double xGB1, double yGB1, double cellSize, double altitudine, double dh, String strFileOutputE, String strFileOutputH, String strFileOutputS, int tipoCampo, int tipoRaster) {
    return libcampoclsJNI.moduloCalcolo_calcoloVert(swigCPtr, this, xGB0, yGB0, xGB1, yGB1, cellSize, altitudine, dh, strFileOutputE, strFileOutputH, strFileOutputS, tipoCampo, tipoRaster);
  }

  public int calcoloPunti(String strFileIndicatori, int tipoCampo) {
    return libcampoclsJNI.moduloCalcolo_calcoloPunti(swigCPtr, this, strFileIndicatori, tipoCampo);
  }

}
